zeflix-dev:
  target: dev
  outputs:
    dev:
      data_source:
        type: bigquery
        method: service-account
        project: zeflix-dev
        dataset: demo
        schema: demo
        location: US 
        keyfile: zeflix-dev-7adb2837b156.json
      quality_output:
        type: bigquery
        method: service-account
        project: zeflix-dev
        dataset: demo
        schema: demo
        location: US
        keyfile: zeflix-dev-7adb2837b156.json