project:
  outputs:
    dev:
      dbname: your_database
      host: localhost
      password: your_password
      port: 5432
      schema: public
      type: postgresql
      user: your_username
    prod:
      dbname: your_database
      host: localhost
      password: your_password
      port: 5432
      schema: prod
      type: postgresql
      user: your_username
    staging:
      dbname: your_database
      host: localhost
      password: your_password
      port: 5432
      schema: staging
      type: postgresql
      user: your_username
  target: dev
