advanced_example:
  target: dev
  outputs:
    dev:
      data_source:
        type: postgresql
        host: postgresql-d18918c8-ob839afc9.database.cloud.ovh.net #postgres-data #{152.252.32.23}
        port: 20184
        user: workshop_user
        password: qc2plus123
        dbname: qc2plus_workshop
        schema: public 

      quality_output:
        type: postgresql
        host: postgresql-d18918c8-ob839afc9.database.cloud.ovh.net #postgres-data #{152.252.32.23}
        port: 20184
        user: workshop_user
        password: qc2plus123
        dbname: qc2plus_workshop
        schema: qc2plus_quality_reports #mettez votre_schema_qualite


