basic_example:
  target: demo
  outputs:
    demo:
      type: postgresql
      host: postgres
      port: 5432
      user: qc2plus
      password: qc2plus_password
      dbname: qc2plus_demo
      schema: demo   # Schéma par défaut est demo (créé par init_tables.sql )